[versions]
kotlin = "2.2.10"
assertj = "3.26.0"
mockito = "5.18.0"
junit = "5.13.4"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
