[versions]
kotlin = "2.2.20"
assertj = "3.27.6"
mockito = "5.20.0"
mockito-kotlin = "6.1.0"
junit = "6.0.1"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
